# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
        description: "Semantic version OR other name to use as image tag"
      pushPass:
        type: string
        required: true
        description: "password for pushing"
      pushUser:
        type: string
        required: true
        description: "username for pushing"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    # runs-on: ${{ matrix.os }}
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.1.5
        with:
          arguments: build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ./build/libs/actiondemo-0.0.1-SNAPSHOT.jar

  push:
    needs: build
    runs-on: ubuntu-latest

    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        name: Download Artifact
        with:
          name: my-artifact
          path: ./artifacts

      - name: Display structure of downloaded files
        run: ls -R

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ inputs.pushUser }}
          password: ${{ inputs.pushPass }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: tylerjgabb/action-demo-repo:v${{ inputs.tag }}
